### PR TITLE
Add Vietnamese language

### PR DESCRIPTION
**Pull request by SITUVNgcd**
Translate bundle to Vietnamese

### CODE REVIEW

**Comment by Darkness6030** [comment]
Lol sorry, didn't see your PR
Need to check it somehow

**Comment by SITUVNgcd** [comment]
> Lol sorry, didn't see your PR Need to check it somehow

Now, you saw it. Thanks.

**Comment by Kowkodivka** [comment]
Hello, thanks for the translation, Darkness forgot to reply, hope it's still up to date

**Comment by SITUVNgcd** [comment]
@Kowkodivka Thank you so much! That help Vietnamese players alot on Crawler mode.

**Pull request merged**
